### ISSUE TITLE
incompatibility with apoli/origins?

### ISSUE THREAD

**Issue by V-lpen** [spoorn/QoLFixes#1]
https://mcpaste.io/c77d4eb10843f357

I attempted to start this mod to fix Presence Footsteps crashing around Shulkers, but it seems to be crashing on startup- heres the error log. It says incompat with apoli.

**Comment by spoorn** [comment]
I'm able to start up minecraft with just Origins and QoLFixes alone.  It's most likely conflicting with another mod.  Is this from a modpack that I can try to reproduce with?  The latest.log file may also say what mods are conflicting

**Comment by spoorn** [comment]
reopen if issue persists
